### ISSUE TITLE
[general comment] is this project out of focus?

### ISSUE THREAD

**Issue by RMHogervorst** [exercism/xr#37]
Since R is a language for statisticians and data scientists, shouldn't data manipulation be more of the focus of this course? Are any packages used in these exercises? At the very least a mention of the tidyverse and tidy principles should be added.

**Comment by jonmcalder** [comment]
I think I see where you are coming from, and I agree that since R is not a general purpose language like most of the other languages represented on exercism that the track for R may need to diverge from other tracks and/or have it's own focus (in places).

My sense for the moment, is that the goal is just to get the R track up and running with a few basic exercises (based on some of the common exercises that have been laid out across multiple language tracks), and then to develop and taylor it further to the language over time. Most of the common exercises are focused on general programming concepts (conditional flow, looping, logic etc) and the idea is to let people explore how to solve these exercises in a particular language - first in their own way and hopefully later via the review process in a way that might be more idiomatic for that specific language. Even though R may not thrive as a language in this kind of general programming space, I think it still presents a great opportunity to learn how to program in R and compare some aspects of the language to other (more general purpose) programming languages. 

In the case of these basic exercises things can usually be done in base R so initially there is no need to involve any particular packages (although of course people are expected to come up with package-specific solutions to different R exercises and compare these with others). In the case of R, I expect later exercises will start to deal with more data related problems (maybe things along the lines of the ETL exercise for example) and those problems will present good opportunities to introduce package specific implementations of solutions etc. 

Tidy principles are growing more and more pervasive in R over time, and I agree that people should be encouraged to learn them, so I'm sure that dplyr, tidyr, purrr etc will feature in solutions to many of the later exercises. At the same time I think it's valuable to consider the pros and cons of different approaches to problems rather than pushing people in a particular direction for everything. As people begin to review solutions to different exercises, hopefully advice can be given on when using a particular package is recommended etc.

Anyway, I've waffled a bit here, so please let me know if I've misinterpreted your comment. I do think this is an important discussion point.

I'm also keen to hear from @kytrinyx, @jonboiser & others how they expect this sort of thing (different focus points for different languages) to play out? I'm still fairly new to exercism so I don't know.

**Comment by RMHogervorst** [comment]
I think you make some excellent points. The focus should be on getting the track ongoing with enough exercises and add more advanced exercises that use packages later on.

**Comment by kytrinyx** [comment]
As of a couple of weeks ago, we have the ability to handle language-specific exercises, so if there are data-manipulation exercises that are not appropriate for any languages other than R, then these can be added to this track exclusively.

On the other hand, some data-manipulation exercises might be interesting in other languages as well, so it is worth considering adding (some of) them to the general pool.

**Comment by RMHogervorst** [comment]
Could also work for python of course. Ill thonk of some exercises

**Comment by jonmcalder** [comment]
@kytrinyx @RMHogervorst Thanks for the reply Katrina! That (language-specific exercises) sounds great, although I agree that many/most data manipulation exercises will be valuable across multiple languages so should be added to the general pool.

**Comment by kytrinyx** [comment]
I'm going to conclude that R is in-scope for Exercism, though there may well be a chunk of custom exercises for it.

Thanks everyone!
